// System tray icon and context menu via the `tray-icon` crate (0.19).
//
// The tray icon must be created on the main thread after the winit event loop
// has been set up (or on Windows it can be created before the loop starts,
// but must be driven from the main thread).
//
// Brand icon pipeline (issue #38):
//   * build.rs renders all icon pixels from `assets/icon-source.webp` at
//     compile time and writes raw 32x32 RGBA8 blobs into OUT_DIR/icons/.
//   * `include_bytes!` brings them into the binary here ... zero runtime
//     image-decode cost and no `image` crate at runtime.
//   * Three logical states: Idle (static), Syncing (frame-cycle every
//     ~100ms), Offline (desaturated + corner slash badge).
//   * Frame cycling is driven externally from `app.rs::run`'s main loop
//     calling `tick_animation()` once per pass; the tray owns the
//     timer + frame index.

use std::sync::mpsc;
use std::time::{Duration, Instant};

use thiserror::Error;
use tray_icon::{
    menu::{Menu, MenuEvent, MenuItem, PredefinedMenuItem},
    Icon, TrayIcon, TrayIconAttributes,
};

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/// The logical state of the tray icon.
#[derive(Debug, Clone, PartialEq)]
pub enum TrayState {
    /// Connected and watching; nothing in queue.
    Idle,
    /// Actively uploading files.
    Syncing { current: u32, total: u32 },
    /// User has paused syncing.
    Paused,
    /// An error has occurred (server unreachable, auth failure, etc.).
    Error(String),
    /// No network / server not reachable.
    Offline,
}

/// User actions emitted by the tray menu.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TrayAction {
    Pause,
    Resume,
    UploadNow,
    OpenSettings,
    About,
    ViewLog,
    ViewTrash,
    CheckForUpdates,
    OpenUpdateDialog,
    RestartToUpdate,
    Quit,
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

#[derive(Debug, Error)]
pub enum TrayError {
    #[error("failed to create tray icon: {0}")]
    IconCreate(String),

    #[error("failed to build tray icon: {0}")]
    Build(String),
}

// ---------------------------------------------------------------------------
// Internal menu item IDs
// ---------------------------------------------------------------------------

const ID_PAUSE: &str = "pause";
const ID_RESUME: &str = "resume";
const ID_UPLOAD_NOW: &str = "upload_now";
const ID_SETTINGS: &str = "settings";
const ID_ABOUT: &str = "about";
const ID_VIEW_LOG: &str = "view_log";
const ID_VIEW_TRASH: &str = "view_trash";
const ID_CHECK_UPDATES: &str = "check_updates";
const ID_UPDATE_AVAILABLE: &str = "update_available";
const ID_RESTART_TO_UPDATE: &str = "restart_to_update";
const ID_QUIT: &str = "quit";

// ---------------------------------------------------------------------------
// Brand icon pixel data (generated by build.rs from assets/icon-source.webp)
// ---------------------------------------------------------------------------

/// Tray icon dimension (square). Must match build.rs::TRAY_SIZE.
pub const TRAY_ICON_SIZE: u32 = 32;
const TRAY_ICON_BYTES: usize = (TRAY_ICON_SIZE as usize) * (TRAY_ICON_SIZE as usize) * 4;

/// Number of frames in the syncing animation. Must match build.rs::ROT_FRAMES.
pub const ROT_FRAME_COUNT: usize = 12;

/// One full rotation per `ROT_PERIOD`. 100ms per frame x 12 frames = 1.2s.
pub const ROT_FRAME_INTERVAL: Duration = Duration::from_millis(100);

const IDLE_RGBA: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/icons/tray_idle.rgba"));
const OFFLINE_RGBA: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/icons/tray_offline.rgba"));

/// All rotation frames. Each is a 32x32 RGBA8 raw bitmap.
///
/// Frame 0 is the canonical orientation (matches `IDLE_RGBA`). Frames 1..11
/// are rotated clockwise in 30 degree increments.
const ROT_FRAMES: [&[u8]; ROT_FRAME_COUNT] = [
    include_bytes!(concat!(env!("OUT_DIR"), "/icons/tray_rot_00.rgba")),
    include_bytes!(concat!(env!("OUT_DIR"), "/icons/tray_rot_01.rgba")),
    include_bytes!(concat!(env!("OUT_DIR"), "/icons/tray_rot_02.rgba")),
    include_bytes!(concat!(env!("OUT_DIR"), "/icons/tray_rot_03.rgba")),
    include_bytes!(concat!(env!("OUT_DIR"), "/icons/tray_rot_04.rgba")),
    include_bytes!(concat!(env!("OUT_DIR"), "/icons/tray_rot_05.rgba")),
    include_bytes!(concat!(env!("OUT_DIR"), "/icons/tray_rot_06.rgba")),
    include_bytes!(concat!(env!("OUT_DIR"), "/icons/tray_rot_07.rgba")),
    include_bytes!(concat!(env!("OUT_DIR"), "/icons/tray_rot_08.rgba")),
    include_bytes!(concat!(env!("OUT_DIR"), "/icons/tray_rot_09.rgba")),
    include_bytes!(concat!(env!("OUT_DIR"), "/icons/tray_rot_10.rgba")),
    include_bytes!(concat!(env!("OUT_DIR"), "/icons/tray_rot_11.rgba")),
];

// Compile-time sanity: build.rs must produce blobs that match the declared
// dimensions. If someone changes TRAY_SIZE in build.rs without touching here,
// the build fails immediately rather than producing a corrupted runtime icon.
const _: () = {
    assert!(IDLE_RGBA.len() == TRAY_ICON_BYTES);
    assert!(OFFLINE_RGBA.len() == TRAY_ICON_BYTES);
    // Can't iterate const arrays in stable const fn yet ... spot-check the
    // first frame; build.rs writes them with a fixed format so if one is
    // right the rest are too.
    assert!(ROT_FRAMES[0].len() == TRAY_ICON_BYTES);
};

/// Build a tray-icon `Icon` from a raw RGBA8 blob of `TRAY_ICON_SIZE` square.
fn icon_from_rgba(rgba: &[u8]) -> Result<Icon, TrayError> {
    // tray-icon takes ownership of the Vec, so we clone the static slice
    // into a fresh allocation each time. Cheap (4 KiB per swap) and lets
    // the static slices stay 'static.
    Icon::from_rgba(rgba.to_vec(), TRAY_ICON_SIZE, TRAY_ICON_SIZE)
        .map_err(|e| TrayError::IconCreate(e.to_string()))
}

/// The RGBA blob for the canonical (frame-0) brand icon. Used by window
/// dialogs that want the static brand mark.
pub fn brand_icon_rgba() -> &'static [u8] {
    IDLE_RGBA
}

/// The RGBA blob and dimensions for the eframe window icon helper in
/// `crate::ui::window_icon`. Exposed so `set_window_icon` can ship the
/// same bitmap that the tray uses.
pub fn brand_icon_dimensions() -> (u32, u32) {
    (TRAY_ICON_SIZE, TRAY_ICON_SIZE)
}

// ---------------------------------------------------------------------------
// Icon selection by logical state
// ---------------------------------------------------------------------------

/// Pick the static icon for a given state. Syncing is animated externally
/// via `tick_animation`, so its still-frame returned here is the current
/// frame index when first entering Syncing (frame 0).
fn static_icon_for_state(state: &TrayState) -> Result<Icon, TrayError> {
    match state {
        TrayState::Idle => icon_from_rgba(IDLE_RGBA),
        TrayState::Syncing { .. } => icon_from_rgba(ROT_FRAMES[0]),
        // Paused / Error / Offline all use the offline overlay variant.
        // Distinct error states differ in tooltip + status text, not in
        // the icon. (Out of scope: a separate "paused" badge variant.)
        TrayState::Paused => icon_from_rgba(OFFLINE_RGBA),
        TrayState::Error(_) => icon_from_rgba(OFFLINE_RGBA),
        TrayState::Offline => icon_from_rgba(OFFLINE_RGBA),
    }
}

fn tooltip_for_state(state: &TrayState) -> String {
    match state {
        TrayState::Idle => "ImmichSync ... Idle".to_owned(),
        TrayState::Syncing { current, total } => {
            format!("ImmichSync ... Uploading {}/{}", current, total)
        }
        TrayState::Paused => "ImmichSync ... Paused".to_owned(),
        TrayState::Error(msg) => format!("ImmichSync ... Error: {}", msg),
        TrayState::Offline => "ImmichSync ... Offline".to_owned(),
    }
}

fn status_text_for_state(state: &TrayState) -> String {
    match state {
        TrayState::Idle => "Idle ... watching for new files".to_owned(),
        TrayState::Syncing { current, total } => {
            format!("Uploading {}/{} files...", current, total)
        }
        TrayState::Paused => "Paused".to_owned(),
        TrayState::Error(msg) => format!("Error: {}", msg),
        TrayState::Offline => "Server offline".to_owned(),
    }
}

// ---------------------------------------------------------------------------
// State machine (next-state transitions + animation cursor)
// ---------------------------------------------------------------------------

/// Returns true if the given pair represents a Syncing -> not-Syncing
/// transition, where the tray icon must snap back to a stable static frame.
fn is_syncing_exit(prev: &TrayState, next: &TrayState) -> bool {
    matches!(prev, TrayState::Syncing { .. }) && !matches!(next, TrayState::Syncing { .. })
}

// ---------------------------------------------------------------------------
// TrayApp
// ---------------------------------------------------------------------------

/// Manages the system tray icon, context menu, and action dispatch.
///
/// # Lifetime
///
/// `TrayApp` must live on the main thread for the duration of the application.
/// Drop it when the event loop exits.
pub struct TrayApp {
    /// The live tray icon handle.  Dropping it removes the icon from the
    /// system tray.
    _tray: TrayIcon,

    /// Current logical state (used for icon / menu updates).
    state: TrayState,

    /// Current server display string (e.g. "photos.example.com [connected]").
    /// Cached for reconnect / status queries; not read internally after assignment.
    #[allow(dead_code)]
    server_status: String,

    /// Index into `ROT_FRAMES` for the next syncing-state icon swap.
    rot_frame: usize,

    /// When the next syncing-state frame swap should happen. `None` when not
    /// in Syncing state.
    next_frame_at: Option<Instant>,

    /// Menu items that may be shown/hidden depending on state.
    pause_item: MenuItem,
    resume_item: MenuItem,
    status_item: MenuItem,
    server_item: MenuItem,
    #[allow(dead_code)]
    check_updates_item: MenuItem,
    update_available_item: MenuItem,
    restart_to_update_item: MenuItem,

    /// Sender half of the action channel.  Cloned into the menu-event handler.
    action_tx: mpsc::Sender<TrayAction>,
}

impl TrayApp {
    /// Create the system tray icon and set up the context menu.
    ///
    /// Returns `(TrayApp, receiver)`.  Poll the receiver on the event loop to
    /// handle user actions.
    pub fn new() -> Result<(Self, mpsc::Receiver<TrayAction>), TrayError> {
        let initial_state = TrayState::Idle;
        let icon = static_icon_for_state(&initial_state)?;

        // ---- Build menu items ----

        // Status line ... disabled (not clickable), updated dynamically.
        let status_item = MenuItem::new(
            status_text_for_state(&initial_state),
            false, // not enabled (display-only)
            None,
        );

        // Server line ... disabled, updated dynamically.
        let server_item = MenuItem::new("Server: (not configured)", false, None);

        // Action items.
        let pause_item = MenuItem::with_id(ID_PAUSE, "Pause Sync", true, None);
        let resume_item = MenuItem::with_id(ID_RESUME, "Resume Sync", false, None);
        let upload_now_item = MenuItem::with_id(ID_UPLOAD_NOW, "Upload Now", true, None);
        let settings_item = MenuItem::with_id(ID_SETTINGS, "Settings", true, None);
        let view_log_item = MenuItem::with_id(ID_VIEW_LOG, "View Upload Log", true, None);
        let view_trash_item = MenuItem::with_id(ID_VIEW_TRASH, "View Trash", true, None);
        let about_item = MenuItem::with_id(ID_ABOUT, "About ImmichSync", true, None);
        let check_updates_item =
            MenuItem::with_id(ID_CHECK_UPDATES, "Check for Updates", true, None);
        let update_available_item =
            MenuItem::with_id(ID_UPDATE_AVAILABLE, "Update Available!", false, None);
        let restart_to_update_item =
            MenuItem::with_id(ID_RESTART_TO_UPDATE, "Restart to Update", false, None);
        let quit_item = MenuItem::with_id(ID_QUIT, "Quit", true, None);

        // ---- Assemble context menu ----

        let menu = Menu::new();

        // "ImmichSync" header ... disabled label.
        let header_item = MenuItem::new("ImmichSync", false, None);

        menu.append(&header_item)
            .map_err(|e| TrayError::Build(e.to_string()))?;
        menu.append(&PredefinedMenuItem::separator())
            .map_err(|e| TrayError::Build(e.to_string()))?;
        menu.append(&status_item)
            .map_err(|e| TrayError::Build(e.to_string()))?;
        menu.append(&PredefinedMenuItem::separator())
            .map_err(|e| TrayError::Build(e.to_string()))?;
        menu.append(&pause_item)
            .map_err(|e| TrayError::Build(e.to_string()))?;
        menu.append(&resume_item)
            .map_err(|e| TrayError::Build(e.to_string()))?;
        menu.append(&upload_now_item)
            .map_err(|e| TrayError::Build(e.to_string()))?;
        menu.append(&PredefinedMenuItem::separator())
            .map_err(|e| TrayError::Build(e.to_string()))?;
        menu.append(&settings_item)
            .map_err(|e| TrayError::Build(e.to_string()))?;
        menu.append(&view_log_item)
            .map_err(|e| TrayError::Build(e.to_string()))?;
        menu.append(&view_trash_item)
            .map_err(|e| TrayError::Build(e.to_string()))?;
        menu.append(&about_item)
            .map_err(|e| TrayError::Build(e.to_string()))?;
        menu.append(&check_updates_item)
            .map_err(|e| TrayError::Build(e.to_string()))?;
        menu.append(&update_available_item)
            .map_err(|e| TrayError::Build(e.to_string()))?;
        menu.append(&restart_to_update_item)
            .map_err(|e| TrayError::Build(e.to_string()))?;
        menu.append(&PredefinedMenuItem::separator())
            .map_err(|e| TrayError::Build(e.to_string()))?;
        menu.append(&server_item)
            .map_err(|e| TrayError::Build(e.to_string()))?;
        menu.append(&PredefinedMenuItem::separator())
            .map_err(|e| TrayError::Build(e.to_string()))?;
        menu.append(&quit_item)
            .map_err(|e| TrayError::Build(e.to_string()))?;

        // ---- Build the tray icon ----

        let tray = TrayIcon::new(TrayIconAttributes {
            tooltip: Some(tooltip_for_state(&initial_state)),
            menu: Some(Box::new(menu)),
            icon: Some(icon),
            ..Default::default()
        })
        .map_err(|e| TrayError::Build(e.to_string()))?;

        // ---- Action channel ----

        let (action_tx, action_rx) = mpsc::channel::<TrayAction>();

        // Subscribe to menu events and forward them through the action channel.
        // tray-icon 0.19 uses a static receiver from MenuEvent::receiver().
        // We spawn a dedicated thread to forward events.
        {
            let tx = action_tx.clone();
            std::thread::spawn(move || {
                let receiver = MenuEvent::receiver();
                loop {
                    match receiver.recv() {
                        Ok(event) => {
                            let action = match event.id().0.as_str() {
                                ID_PAUSE => Some(TrayAction::Pause),
                                ID_RESUME => Some(TrayAction::Resume),
                                ID_UPLOAD_NOW => Some(TrayAction::UploadNow),
                                ID_SETTINGS => Some(TrayAction::OpenSettings),
                                ID_ABOUT => Some(TrayAction::About),
                                ID_VIEW_LOG => Some(TrayAction::ViewLog),
                                ID_VIEW_TRASH => Some(TrayAction::ViewTrash),
                                ID_CHECK_UPDATES => Some(TrayAction::CheckForUpdates),
                                ID_UPDATE_AVAILABLE => Some(TrayAction::OpenUpdateDialog),
                                ID_RESTART_TO_UPDATE => Some(TrayAction::RestartToUpdate),
                                ID_QUIT => Some(TrayAction::Quit),
                                _ => None,
                            };
                            if let Some(a) = action {
                                tracing::debug!("tray action: {:?}", a);
                                if tx.send(a).is_err() {
                                    // Main thread has dropped the receiver; exit.
                                    break;
                                }
                            }
                        }
                        Err(_) => break, // channel closed
                    }
                }
            });
        }

        tracing::info!("system tray icon created");

        let app = Self {
            _tray: tray,
            state: initial_state,
            server_status: "Server: (not configured)".to_owned(),
            rot_frame: 0,
            next_frame_at: None,
            pause_item,
            resume_item,
            status_item,
            server_item,
            check_updates_item,
            update_available_item,
            restart_to_update_item,
            action_tx,
        };

        Ok((app, action_rx))
    }

    /// Update the tray icon and status text based on the new state.
    pub fn update_state(&mut self, state: TrayState) {
        // Bail out if the state is genuinely unchanged ... avoids re-setting
        // the same icon every 2s on the stats loop.
        if self.state == state {
            return;
        }

        tracing::debug!("tray state -> {:?}", state);

        let was_syncing_exit = is_syncing_exit(&self.state, &state);

        // Update icon.
        if let Ok(icon) = static_icon_for_state(&state) {
            let _ = self._tray.set_icon(Some(icon));
        }

        // Snap the rotation cursor on any non-syncing entry so a future
        // Syncing entry always starts from the canonical frame 0.
        if was_syncing_exit {
            self.rot_frame = 0;
            self.next_frame_at = None;
        }

        // Entering syncing: start the rotation timer.
        match &state {
            TrayState::Syncing { .. } => {
                self.rot_frame = 0;
                self.next_frame_at = Some(Instant::now() + ROT_FRAME_INTERVAL);
            }
            _ => {
                self.next_frame_at = None;
            }
        }

        // Update tooltip.
        let _ = self._tray.set_tooltip(Some(tooltip_for_state(&state)));

        // Update status line text.
        self.status_item.set_text(status_text_for_state(&state));

        // Show pause vs. resume depending on state.
        match &state {
            TrayState::Paused => {
                self.pause_item.set_enabled(false);
                self.resume_item.set_enabled(true);
            }
            _ => {
                self.pause_item.set_enabled(true);
                self.resume_item.set_enabled(false);
            }
        }

        self.state = state;
    }

    /// Advance the syncing-state animation cursor if the frame interval has
    /// elapsed. Cheap no-op when the tray is not in Syncing state.
    ///
    /// Call from the main loop on every pass.
    pub fn tick_animation(&mut self) {
        let Some(deadline) = self.next_frame_at else {
            return;
        };
        let now = Instant::now();
        if now < deadline {
            return;
        }

        // Compute how many frames we should advance. If the loop stalled
        // longer than one interval, skip frames rather than play catch-up ...
        // a smooth-looking 5-frame burst after a long pause reads worse than
        // jumping to the current frame.
        let elapsed = now.duration_since(deadline);
        let skip = (elapsed.as_millis() / ROT_FRAME_INTERVAL.as_millis()) as usize;
        let advance = 1 + skip;

        self.rot_frame = (self.rot_frame + advance) % ROT_FRAME_COUNT;
        // Schedule next swap from `now` (not `deadline`) to avoid runaway
        // catch-up after a long pause.
        self.next_frame_at = Some(now + ROT_FRAME_INTERVAL);

        if let Ok(icon) = icon_from_rgba(ROT_FRAMES[self.rot_frame]) {
            let _ = self._tray.set_icon(Some(icon));
        }
    }

    /// Update the server connection line in the tray menu.
    ///
    /// `url` should be just the hostname or a short display form
    /// (e.g. `"photos.example.com"`).
    pub fn set_server_status(&mut self, url: &str, connected: bool) {
        let status = if connected {
            format!("Server: {} [connected]", url)
        } else {
            format!("Server: {} [offline]", url)
        };
        tracing::debug!("tray server status: {}", status);
        self.server_item.set_text(&status);
        self.server_status = status;
    }

    /// Show or hide the "Update Available!" menu item.
    ///
    /// When `version` is `Some`, the item is shown with the version in the
    /// label text. When `None`, the item is hidden (disabled).
    pub fn set_update_available(&mut self, version: Option<&str>) {
        match version {
            Some(v) => {
                self.update_available_item
                    .set_text(&format!("Update Available (v{v})!"));
                self.update_available_item.set_enabled(true);
            }
            None => {
                self.update_available_item.set_text("Update Available!");
                self.update_available_item.set_enabled(false);
            }
        }
    }

    /// Show or hide the "Restart to Update" menu item.
    ///
    /// When `version` is `Some`, the item is shown and the "Update Available!"
    /// item is hidden (download is already done). When `None`, the item is hidden.
    pub fn set_restart_to_update(&mut self, version: Option<&str>) {
        match version {
            Some(v) => {
                self.restart_to_update_item
                    .set_text(&format!("Restart to Update (v{v})"));
                self.restart_to_update_item.set_enabled(true);
                // Hide the "Update Available" item since the download is done.
                self.update_available_item.set_text("Update Available!");
                self.update_available_item.set_enabled(false);
            }
            None => {
                self.restart_to_update_item.set_text("Restart to Update");
                self.restart_to_update_item.set_enabled(false);
            }
        }
    }

    /// Return a clone of the action sender, useful for injecting actions
    /// programmatically (e.g. from a device event thread).
    pub fn action_sender(&self) -> mpsc::Sender<TrayAction> {
        self.action_tx.clone()
    }

    /// Current state. For tests.
    #[cfg(test)]
    pub fn state(&self) -> &TrayState {
        &self.state
    }

    /// Current rotation cursor. For tests.
    #[cfg(test)]
    pub fn rot_frame(&self) -> usize {
        self.rot_frame
    }
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn frame_set_has_twelve_frames_of_correct_size() {
        assert_eq!(ROT_FRAMES.len(), ROT_FRAME_COUNT);
        for (i, frame) in ROT_FRAMES.iter().enumerate() {
            assert_eq!(
                frame.len(),
                TRAY_ICON_BYTES,
                "frame {} has wrong byte count",
                i
            );
        }
    }

    #[test]
    fn idle_and_offline_blobs_are_correct_size() {
        assert_eq!(IDLE_RGBA.len(), TRAY_ICON_BYTES);
        assert_eq!(OFFLINE_RGBA.len(), TRAY_ICON_BYTES);
    }

    #[test]
    fn frame_zero_matches_idle_blob() {
        // Idle and the canonical (un-rotated) frame are rendered from the
        // same source by build.rs ... they must be byte-identical so that
        // entering and leaving Syncing doesn't visibly twitch.
        assert_eq!(ROT_FRAMES[0], IDLE_RGBA);
    }

    #[test]
    fn offline_blob_differs_from_idle() {
        // Sanity: the offline overlay must visibly differ from idle.
        assert_ne!(IDLE_RGBA, OFFLINE_RGBA);
    }

    #[test]
    fn syncing_to_idle_is_detected_as_exit() {
        let prev = TrayState::Syncing {
            current: 1,
            total: 5,
        };
        let next = TrayState::Idle;
        assert!(is_syncing_exit(&prev, &next));
    }

    #[test]
    fn syncing_to_syncing_is_not_an_exit() {
        let prev = TrayState::Syncing {
            current: 1,
            total: 5,
        };
        let next = TrayState::Syncing {
            current: 2,
            total: 5,
        };
        assert!(!is_syncing_exit(&prev, &next));
    }

    #[test]
    fn syncing_to_offline_is_detected_as_exit() {
        let prev = TrayState::Syncing {
            current: 1,
            total: 5,
        };
        let next = TrayState::Offline;
        assert!(is_syncing_exit(&prev, &next));
    }

    #[test]
    fn idle_to_idle_is_not_an_exit() {
        // No syncing involved.
        assert!(!is_syncing_exit(&TrayState::Idle, &TrayState::Idle));
    }

    #[test]
    fn offline_to_idle_is_not_a_syncing_exit() {
        assert!(!is_syncing_exit(&TrayState::Offline, &TrayState::Idle));
    }
}
